### ISSUE TITLE
[feature request] follow users

### ISSUE THREAD

**Issue by disrupted** [WangDaYeeeeee/Mysplash#10]
I am not sure if this feature is still in beta, but recently Unsplash introduced a new feature to their page that finally lets you follow specific photographers (just like you would on other social networks). Would be cool if this functionality could come to Mysplash as well.

**Comment by WangDaYeeeeee** [comment]
It's in test now.

**Comment by hullymoly** [comment]
Will this feature come? When will he come?

**Comment by WangDaYeeeeee** [comment]
In this week, probably.

**Comment by disrupted** [comment]
_early feedback about update 2.8.3 here:_
@WangDaYeeeeee dude, you nailed it with this update. loving the new follow option and this is about the most gorgeous button animation I've ever seen. big ups !

**Comment by WangDaYeeeeee** [comment]
Thank you dude.~
