### ISSUE TITLE
v2.8.8 can't like pictures anymore

### ISSUE THREAD

**Issue by disrupted** [WangDaYeeeeee/Mysplash#18]
the latest update which "improves some of the logic behind liking pictures" actually broke it for me. the tiny spinner comes up for a second but the picture remains without a like. Have tried it with both official and custom API keys. Can you please check if everything is technically fine?

**Comment by WangDaYeeeeee** [comment]
Is that cannot work in every view? Or just some view?

**Comment by disrupted** [comment]
ah you know what, my bad, somehow I got logged out – actually works like a charm as ever. (and I should get more sleep)
+++ thanks, can be closed
