### ISSUE TITLE
Load nothing

### ISSUE THREAD

**Issue by mahdiG** [WangDaYeeeeee/Mysplash#20]
Hi. Version 2.8.9 doesn't load any image.

**Comment by WangDaYeeeeee** [comment]
Well, I have already send a new update.

mahdiG <notifications@github.com>于2017年2月12日周日 21:02写道：

**Comment by mahdiG** [comment]
Really? The latest version in F-Droid is 2.8.9

**Comment by WangDaYeeeeee** [comment]
You can find it in google play, and I never send a update version to F-Droid...

**Comment by mahdiG** [comment]
So who updates the f-droid version?? I don't have google play :-/

**Comment by wisemonkey** [comment]
Just confirming the issue with f droid version.

**Comment by rugk** [comment]
FDroid updates automatically… They pull the code by themself…

**Comment by rugk** [comment]
BTW  @WangDaYeeeeee could you clean up (= close) all this dupes of "nothing loaded"?

https://github.com/WangDaYeeeeee/Mysplash/issues/9, https://github.com/WangDaYeeeeee/Mysplash/issues/17
