### ISSUE TITLE
[idea] show remaining API requests

### ISSUE THREAD

**Issue by disrupted** [WangDaYeeeeee/Mysplash#21]
Would it be possible to show the remaining API requests for this hour somewhere in the app (for instance inside the left panel)? as far as I understand their documentation you always receive something like
```
200 OK
X-Ratelimit-Limit: 1000
X-Ratelimit-Remaining: 999
```
as part of their HTTP Response header.
At this point when you know the global limit it would also be possible to just count the requests locally, right? I think this might be a good way to handle the current situation with the rate limiting.

**Comment by WangDaYeeeeee** [comment]
Well, I think this is unnecessary.

The Mysplash's API key has 5000 request times in every hour. It's a huge number, and it's enough to use. If you request a personal API key, it would have 500 request time in every hour, it's enough too.

**Comment by rugk** [comment]
I agree, so we can we close this issue?
