### ISSUE TITLE
strange placeholder launcher icons on image viewer

### ISSUE THREAD

**Issue by disrupted** [WangDaYeeeeee/Mysplash#25]
this happens when I tap once inside the new image viewer. (v2.9.5)
[http://i.imgur.com/3GQFtOI.jpg](http://i.imgur.com/3GQFtOI.jpg)

**Comment by WangDaYeeeeee** [comment]
This is a function to preview the wallpaper. You can tap the image to let them show or hide.

**Comment by disrupted** [comment]
oh okay, then that's pretty cool actually. I simply wasn't aware of this.
