### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by CrimsonFork** [WangDaYeeeeee/Mysplash#30]
I've translated your app to [German](https://gist.github.com/77d3d88c77eaf5fef073a471e089230c) via [Stringlate](https://github.com/LonamiWebs/Stringlate).

You may have to have a look at it first because I've translated some Strings with an underscore which I guess I'm not supposed to.

**Comment by WangDaYeeeeee** [comment]
Sorry to reply to you so late, I'm really busy this month.

I've alreay sent a new update to the Google play, and added the German language.
Really thank you for the translate work man. Have a nice day.

**Comment by CrimsonFork** [comment]
No problem for me waiting for an answer, don't worry!

I'm using only F-Droid by the way.

**Comment by CrimsonFork** [comment]
I made an [update](https://gist.github.com/321a55cfa0ad86b562b8574a86390e13) for the translation and noticed that you linked me in the translator credits, thanks :-)

**Comment by rugk** [comment]
@OffifialMITX Instead of gists, pull requests would be more useful, would not they?

**Comment by CrimsonFork** [comment]
You may be totally right but...
... [Stringlate](https://github.com/LonamiWebs/Stringlate) doesn't support PRs
... I have absolutely no idea how to use GitHub functions which are not Star/Download/Comment/New Issue. I will learn it once but in the I don't have enough time yet. I'll put it on my ToDo list though, thanks.

**Comment by rugk** [comment]
It's easy to learn – and clearly useful.

@WangDaYeeeeee, you could of course also use some online-translation service and integrate it here, so users can just use it to translate your app into multiple languages.

**Comment by mueller-ma** [comment]
Sorry to say that, but you translation is not very good. Many gramar mistakes, e.g. "Betrieben vo**u**n Unsplash.com" and often you use unsuitable words, e.g. "VERFOLGER". A "verfolger" is a hunter, not a follower

**Comment by CrimsonFork** [comment]
The grammar mistakes are most likely because of my small keyboard and you're right, after a while I stopped thinking about the actual meaning of what I'm translating. Thank you for pointing this out, ~~I'm going to take a look at this in the next few days~~ .

**Comment by CrimsonFork** [comment]
Thanks to @mueller-ma the [translation](https://gist.github.com/2d9a75898dd70f3d9c5b548e8212b62f) is now better. I've made about 15 changes.

Please set the version number as a non-translateable string. I just had to make this change manually.

**Comment by rugk** [comment]
So what about a PR finally? For easy PRs you can also user GitHub desktop, if possible.
I can also have a look at the translation then.

**Comment by mueller-ma** [comment]
I have made a PR yesterday with some corrections #44

**Comment by mueller-ma** [comment]
@OffifialMITX Can be closed?

**Comment by CrimsonFork** [comment]
I don't have anything against it.
