### ISSUE TITLE
Russian language support

### ISSUE THREAD

**Issue by Ulop** [WangDaYeeeeee/Mysplash#32]
russian language translation(values-ru)
rename to strings.xml
[strings-ru.txt](https://github.com/WangDaYeeeeee/Mysplash/files/823805/strings-ru.txt)
[arrays](https://gist.github.com/Ulop/86b15cf981fbb5ab72e51bf2e1d834e5)

**Comment by WangDaYeeeeee** [comment]
Man, I just saw your issue, I will add Russian language in next version.

Thank you for the translate work.

**Comment by Ulop** [comment]
I'm make some changes. Please look my comment on values-ru/strings.xml in this [commit](https://github.com/WangDaYeeeeee/Mysplash/commit/3b6fe70a7534c2649f97ce9346673569541670be#diff-76bcd6883af6cc94358142cc50166062).
