### ISSUE TITLE
Muzei: add option for setting resolution

### ISSUE THREAD

**Issue by anuraag488** [WangDaYeeeeee/Mysplash#74]
Hi
When using muzei wallpaper service, can you add an option to set wallpaper size.
It will help save bandwidth for those who don't use scrolling wallpaper. 
Url for api
_Unsplash_api_url_/photos/_photoid_?h=1920&w=1080"

**Comment by anuraag488** [comment]
@WangDaYeeeeee
"Added screen size image option in Muzei Settings."
This option still download full resolution of image.

**Comment by WangDaYeeeeee** [comment]
That may be because muzei has already cached some artwork information
before you change the settings. Just click the next button a few times.

neodada <notifications@github.com> 于2019年5月27日周一 下午4:44写道：

**Comment by anuraag488** [comment]
Ok working.

**Comment by anuraag488** [comment]
@WangDaYeeeeee
In case if you like to add one more source for muzei
source : search term
search terms : pattern,texture,abstract
url : https://api.unsplash.com/photos/random?query=pattern,texture,abstract&featured=false&count=10

**Comment by WangDaYeeeeee** [comment]
👌

neodada <notifications@github.com> 于2019年5月29日周三 上午9:21写道：
