### ISSUE TITLE
About Bugly

### ISSUE THREAD

**Issue by adolfintel** [WangDaYeeeeee/Mysplash#77]
I see you're using Bugly for crash reporting.

I hate to nag yet another developer about this, but because of GDPR laws, if you want to distribute this in the EU you need to ask the user for consent BEFORE initializing Bugly. Currently you don't have a way to opt-out or even a disclaimer, and this is in full violation of GDPR, you might get in trouble because of this.

(personally, I recommend simply removing it)

**Comment by WangDaYeeeeee** [comment]
Thanks for your feedback, I will check it.

Federico Dossena <notifications@github.com> 于2019年9月27日周五 上午1:35写道：

**Comment by adolfintel** [comment]
Any news about this? The app will get removed from F-Droid if you don't do anything because the library is proprietary.

**Comment by WangDaYeeeeee** [comment]
I will push a new version very soon.

Federico Dossena <notifications@github.com> 于2019年10月5日周六 上午2:03写道：

**Comment by adolfintel** [comment]
I see you removed Bugly, that's awesome.
You should also update the manifest for your app on f-droid, because it's still on 3.7.1 (or I can do it for you)

**Comment by WangDaYeeeeee** [comment]
Of course you can, thanks a lot.
Also I want to ask, will f-droid automatically publish a new version
according to my release record on github?

Federico Dossena <notifications@github.com> 于2019年10月10日周四 下午2:40写道：
